from java import *
from code.Proxy import PyJinnProxy
from main import ContainerLayout
from main import ContainerLayout
from minescript import ItemStack

class Waypoint:
    def __init__(self, name: str, initials: str, x: int, y: int, z: int, index: int = 0, set_name: str = ""): ...
    name: str
    initials: str
    x: int
    y: int
    z: int
    index: int
    set_name: str
        
class XaeroHelper(PyJinnProxy):
    @staticmethod
    def is_mod_loaded() -> bool: ...
    @staticmethod
    def get_current_minimap_session() -> JavaObject | None: ...
    @staticmethod
    def get_current_world_manager() -> JavaObject | None: ...
    @staticmethod
    def get_current_world() -> JavaObject | None: ...
    @staticmethod
    def get_current_waypoint_set() -> JavaObject | None: ...
    @staticmethod
    def get_current_waypoint_set_name() -> str | None: ...
    @staticmethod
    def get_current_set_waypoints() -> List[Waypoint] | None:  ...
    @staticmethod
    def add_waypoint_to_current_set(name: str, x: float|int, y: float|int, z: float|int, initials: str) -> bool | None: ...
    @staticmethod
    def remove_waypoint_from_current_set(waypoint: Waypoint | int) -> bool: ...
    @staticmethod
    def get_waypoint_from_current_set(waypoint: Waypoint | int) -> Waypoint | None: ...
    @staticmethod
    def get_current_waypoint_set_count() -> int | None: ...
    
class BookScreenHelper(PyJinnProxy):

    @staticmethod
    def is_edit_book_screen() -> bool: ...
    @staticmethod
    def is_view_book_screen() -> bool: ...
    @staticmethod
    def is_book_screen() -> bool: ...
    @staticmethod
    def get_page_count() -> int | None: ...
    @staticmethod
    def get_current_page_index() -> int | None: ...
    @staticmethod
    def is_last_page() -> bool | None: ...
    @staticmethod
    def page_forward() -> None: ...
    @staticmethod
    def page_back() -> None: ...
  
class GLFWHelper(PyJinnProxy):
    @staticmethod
    def get_cursor_gui_position() -> Vec2: ...
    @staticmethod
    def get_cursor_position() -> Vec2: ...
    @staticmethod
    def set_cursor_position(x: float, y: float): ...
    @staticmethod
    def show_cursor(): ...
    @staticmethod
    def hide_cursor(): ...
    @staticmethod
    def disable_cursor(): ...
    @staticmethod
    def is_cursor_hidden_or_disabled() -> bool: ...
    @staticmethod
    def is_mouse_button_pressed(button: int) -> bool: ...
    @staticmethod
    def send_mouse_button(button: int, press: bool): ...
  
class WindowHelper(PyJinnProxy):
    @staticmethod
    def get_window_handle() -> JavaObject: ...
    @staticmethod
    def is_window_fullscreen() -> bool: ...
    @staticmethod
    def is_window_minimized() -> bool: ...
    @staticmethod
    def get_position() -> Vec2: ...
    @staticmethod
    def get_size() -> WindowSize: ...
    @staticmethod
    def get_screen_size() -> WindowSize: ...
    @staticmethod
    def get_gui_size() -> WindowSize: ...
    @staticmethod
    def get_aspect_ratio() -> float: ...
    @staticmethod
    def get_gui_scale() -> float: ...
    @staticmethod
    def get_coordinate_scale(window_to_gui: bool = False) -> Vec2: ...
    @staticmethod
    def get_screen_position(gui_x: float, gui_y: float) -> Vec2: ...
    @staticmethod
    def get_gui_position(window_x: float, window_y: float) -> Vec2: ...

class EnchantmentInfo:
    id: int
    name: str
    level: int
    costs: int

class BlocksHelper(PyJinnProxy):
  @staticmethod
  def get_block_pos(x: int|float, y: int|float|None = None, z: int|float|None = None) -> JavaObject: ...
  @staticmethod
  def get_block_state(x: int|float|JavaObject, y: int|float|None = None, z: int|float|None = None) -> JavaObject: ...
  @staticmethod
  def get_block_state_block(block_state: JavaObject) -> JavaObject: ...
  @staticmethod
  def get_block_state_json(block_state: JavaObject) -> str: ...
  @staticmethod
  def get_block_entity(x: int|float|JavaObject, y: int|float|None = None, z: int|float|None = None) -> JavaObject: ...
  @staticmethod
  def is_command_block_entity(block_entity: JavaObject) -> bool: ...
  @staticmethod
  def set_command_block_entity_command(command_block_entity: JavaObject, command: str) -> bool: ...
  @staticmethod
  def get_command_block_entity_command(command_block_entity: JavaObject) -> str | None: ...
  @staticmethod
  def get_command_block_entity_last_output(command_block_entity: JavaObject) -> str | None: ...
  @staticmethod
  def get_command_block_entity_mode(command_block_entity: JavaObject) -> str | None: ...
  @staticmethod
  def is_command_block_entity_conditions_met(command_block_entity: JavaObject) -> bool | None: ...
  @staticmethod
  def is_command_block_entity_powered(command_block_entity: JavaObject) -> bool | None: ...
  @staticmethod
  def is_command_block_entity_automatic(command_block_entity: JavaObject) -> bool | None: ...
  @staticmethod
  def get_jukebox_block_entity_item(jukebox_block_entity: JavaObject) -> JavaObject | None: ...
  @staticmethod
  def get_jukebox_block_entity_ticks_since_song_started(jukebox_block_entity: JavaObject) -> int | None: ...
  @staticmethod
  def is_jukebox_block_entity_song_playing(jukebox_block_entity: JavaObject) -> bool | None: ...
  
class MappingsHelper(PyJinnProxy):
  @staticmethod
  def get_runtime_class_name(pretty_class_name: str) -> str: ...

  @staticmethod
  def get_pretty_class_name(runtime_class_name: str) -> str: ...

  @staticmethod
  def get_runtime_field_name(clazz: JavaObject, pretty_field_name: str) -> str: ...

  @staticmethod
  def get_pretty_field_names(clazz: JavaObject) -> JavaObject: ...

  @staticmethod
  def get_runtime_method_names(clazz: JavaObject, pretty_method_name: str) -> JavaObject: ...

  @staticmethod
  def get_pretty_method_names(clazz: JavaObject) -> JavaObject: ...


class ReflectionHelper(PyJinnProxy):
  @staticmethod
  def get_private_field(instance: JavaObject, pretty_field_name: str) -> Any: ...
  @staticmethod
  def set_private_field(instance, pretty_field_name, value) -> bool: ...
  @staticmethod
  def get_declared_method_accessible(instance, pretty_method_name): ...
  @staticmethod
  def invoke_private_method(instance, pretty_method_name, *args): ...
  
class ItemsHelper(PyJinnProxy):  
  @staticmethod
  def get_item_id(item: JavaObject | str | int) -> str | None: ...

  @staticmethod
  def get_numeric_id(item: JavaObject | str | int) -> int: ...

  @staticmethod
  def get_display_name(item: JavaObject | str | int, use_custom_name: bool = False) -> str | None:  ...

  @staticmethod
  def get_count(item: JavaObject | str | int) -> int: ...

  @staticmethod
  def get_max_stack_size(item: JavaObject | str | int) -> int: ...

  @staticmethod
  def get_item_stack_java_object(item: JavaObject | str | int) -> JavaObject: ...

  @staticmethod
  def get_item_java_object(item: JavaObject | str | int) -> JavaObject: ...

  @staticmethod
  def get_json(item: JavaObject | str | int) -> str: ...

  @staticmethod
  def get_components(item: JavaObject | str | int) -> str: ...


class ContainerHelper(PyJinnProxy): 
  @staticmethod
  def enchantment_table_get_enchant_info(enchantment_apply_type) -> EnchantmentInfo|None: ...
  @staticmethod
  def enchantment_table_apply_enchant(enchantment_apply_type) -> bool: ...

  @staticmethod
  def get_container() -> JavaObject | None: ...
  @staticmethod
  def get_container_class_name() -> str: ...

  @staticmethod
  def get_container_id() -> int: ...

  @staticmethod
  def get_container_slot(slot: int) -> ItemStack | None: ...

  @staticmethod
  def get_inventory_slot(slot: int) -> ItemStack | None:...

  @staticmethod
  def get_item_stack_by_inventory_slot(slot: int) -> JavaObject | None: ...

  @staticmethod
  def get_item_stack_by_container_slot(slot: int) -> JavaObject | None: ...

  @staticmethod
  def container_find_item_id(item_id: str) -> list[JavaObject]: ...

  @staticmethod
  def inventory_find_item_id(item_id: str) -> list[JavaObject]: ...

  @staticmethod
  def raw_click(slot: int, button_or_slot: int = 0, click_type: str | None = ...) -> bool: ...

  @staticmethod
  def click_slot(slot: int, button: int = 0) -> bool: ...

  @staticmethod
  def shift_click_slot(slot: int) -> bool: ...

  @staticmethod
  def click_swap_with_hotbar(slot: int, hotbar_slot: int) -> bool: ...

  @staticmethod
  def pickup_swap_container(slot_a: int, slot_b: int) -> bool: ...

  @staticmethod
  def get_inventory_selected_hotbar_slot() -> int: ...

  @staticmethod
  def get_inventory_free_slot() -> int | None: ...
  @staticmethod
  def get_slot_screen_position(slot: int) -> Vec2 | None: ...
  @staticmethod
  def get_container_layout() -> ContainerLayout | None: ...

class FishingHelper(PyJinnProxy):
  @staticmethod
  def is_holding_rod() -> bool: ...

  @staticmethod
  def is_casted() -> bool: ...

  @staticmethod
  def is_biting() -> bool | None: ...

  @staticmethod
  def is_open_water() -> bool | None: ...

  @staticmethod
  def get_hooked_entity() -> Any: ...

  @staticmethod
  def get_time_until_lured() -> int | None: ...

  @staticmethod
  def get_time_until_hooked() -> int | None: ...

  @staticmethod
  def use_rod() -> bool: ...


class ClientHelper(PyJinnProxy):
  @staticmethod
  def set_current_screen(screen: JavaObject) -> None: ...

  @staticmethod
  def get_current_screen() -> JavaObject | None: ...

  @staticmethod
  def get_current_screen_class_name() -> str: ...

  @staticmethod
  def close_current_screen(with_close_container_packet: bool = True) -> None: ...

  @staticmethod
  def open_pause_screen() -> None: ...

  @staticmethod
  def open_inventory_screen() -> None: ...

  @staticmethod
  def disconnect(str: str = "Disconnected by Minescript") -> None: ...

  @staticmethod
  def get_level_data() -> ClientLevelData: ...

  @staticmethod
  def get_fps() -> int: ...

  @staticmethod
  def get_camera_position() -> Vec3: ...
  @staticmethod
  def get_camera_block_position() -> Vec3: ...

  @staticmethod
  def get_camera_type() -> str:
    """
    FIRST_PERSON, THIRD_PERSON_BACK, THIRD_PERSON_FRONT
    """
    ...
    
  @staticmethod
  def show_toast(title: str, desc: str, display_time: float = 5000.0): ...
  @staticmethod
  def is_any_toast_showing() -> bool: ...
  @staticmethod
  def narrate_text(text: str): ...


class ClientLevelData(PyJinnProxy):
  hardcore: bool
  is_flat: bool
  game_time: int
  day_time: int
  raining: bool
  difficulty: str
  difficulty_locked: bool

  def __init__(self, hardcore: bool, is_flat: bool, game_time: int, day_time: int, raining: bool, difficulty: str, difficulty_locked: bool) -> None: ...


class UtilHelper(PyJinnProxy):
  @staticmethod
  def get_class_name(obj: JavaObject) -> str: ...
  @staticmethod
  def get_clipboard() -> str: ...
  @staticmethod
  def set_clipboard(text: str) -> None: ...

class RegistryHelper(PyJinnProxy):
  @staticmethod
  def get_by_id(registry: JavaObject, identifier: str) -> JavaObject: ...
  @staticmethod
  def get_registry_path(registry_name: str) -> JavaObject: ...


class Vec3:
  x: float
  y: float
  z: float

class Vec2:
  def __init__(self, x: float, y: float) -> None: ...
  x: float
  y: float
  
class WindowSize:
  width: float
  height: float
  
class MerchantHelper(PyJinnProxy):
  @staticmethod
  def is_container_merchant() -> bool: ...
  @staticmethod
  def get_offers_json() -> str | None: ...
  @staticmethod
  def set_selected_trade_index(index: int) -> bool | None: ...
  @staticmethod
  def get_xp() -> int | None: ...
  @staticmethod
  def get_total_xp_needed_for_level_up() -> int | None: ...
  @staticmethod
  def get_level() -> int | None: ...